version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 768912473174.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=768912473174.dkr.ecr.eu-central-1.amazonaws.com/backend_v3
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI="$REPOSITORY_URI:$IMAGE_TAG"
  build:
    commands:
      - docker-compose build
      - docker tag src-app:latest $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      - echo "Image pushed to ECR with tag $IMAGE_TAG"
      - |
        printf '{"AWSEBDockerrunVersion": "1", "Image": {"Name": "%s", "Update": "true"}, "Ports": [{"ContainerPort": "80"}]}' "$IMAGE_URI" > Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
  discard-paths: yes
